Ft/nav bar
DevRamona/the_Baumesiter pull request #11
Opened 2024-05-28 15:55 UTC by Kevin-gram

Renaming the navbar branch to nav-bar

2024-05-29 15:25 UTC, brendahuwitonze approved these changes

2024-05-29 15:26 UTC, DevRamona requested changes
How about you put the lg:hidden as the last so that your codes are written in ascending order?

2024-05-29 15:44 UTC, DevRamona approved these changes
It looks good.

2024-05-31 21:22 UTC, peninah98 requested changes
Feel free to work on changes and you can merge on develop when you are done

2024-05-31 21:22 UTC, peninah98 commented on index.html
> +    <div id="navbar" class="sticky w-full top-0 z-10 bg-bgPrimary"></div>
Can you change the name of this customized background color? `bg-bgPrimary` doesn't make sense.

2024-05-31 21:22 UTC, peninah98 commented on src/sections/greenNav.html
> +    <div class=" text-3xl lg:text-5xl font-bold relative">
Can you remove the space before the tailwind classes? There is no role it is serving.

2024-05-31 21:22 UTC, peninah98 commented on src/sections/greenNav.html
> +        <img src="/src/sections/img/Vector-5.webp" alt="menu-image" class=" md:hidden lg:hidden w-48 h-14">
This space should be removed.
 I see that you want to hide it on medium and large screens, could you try to apply it only to medium and check what will happen to large screens too?

2024-05-31 21:22 UTC, peninah98 commented on src/sections/greenNav.html
> +<div class="hidden md:hidden lg:block">
This hidden class is duplicated.

2024-05-31 21:22 UTC, peninah98 commented on src/sections/navbar.html
> +        <img src="/src/sections/img/Vector-5.webp" alt="menu-image" class="md:hidden w-48 h-14 lg:hidden">
Hidden is duplicated. ` class="md:hidden w-48 h-14 lg:hidden"`

2024-05-31 21:22 UTC, peninah98 commented on src/sections/navbar.html
> +        <p class="absolute left-4 top-2 text-smallSize md:text-5xl md:relative lg:relative lg:text-5xl">Baumeister</p>
Duplicated class names `md:relative lg:relative`

2024-05-31 21:22 UTC, peninah98 commented on src/sections/navbar.html
> +<div class="hidden md:hidden lg:block">
Duplicates again.

2024-05-31 21:22 UTC, peninah98 commented on tailwind.config.js
> +        navsize: "0.9375rem",
Using camel case in as naming will easy code base readability as well as stick to the consistency.

2024-05-31 21:22 UTC, peninah98 commented on src/sections/navbar.html
> +    <div class="flex flex-col text-smallerSize md:text-2xl"><h1>DE</h1><p>EN</p></div>
You can install code format to make format codes.

2024-05-31 21:22 UTC, peninah98 commented on src/sections/navbar.html
> +    <div class="flex flex-col text-smallerSize md:text-2xl"><h1>DE</h1><p>EN</p></div>
`<h1>DE</h1><p>EN</p>`, keep consistency on tags you are using if is h1 or p.

2024-06-03 15:04 UTC, peninah98 commented on tailwind.config.js
> +        smallSize:"2rem",
Why do we have smaller and smallSize in as fontsize?

2024-06-04 08:10 UTC, brendahuwitonze approved these changes
I think all is good

2024-06-04 12:09 UTC, Gihozo23 reviewed
I have added two reviews on the footer.html check them out.

2024-06-04 12:09 UTC, Gihozo23 commented on src/sections/navbar.html
> +<div class="bg-PrimaryColor flex justify-between p-4 fixed w-full top-0 z-10">
you can increase the padding (pt or py) because the vertical space above the nav bar from the figma page is larger than the one we have here.

2024-06-04 12:09 UTC, Gihozo23 commented on src/sections/navbar.html
> +    </div>
Here, the font-weight is regular so rather than using font-semibold you can try font-light and see if it's more suitable

2024-06-05 13:07 UTC, peninah98 approved these changes

2024-06-05 13:08 UTC, merged