feat: create the about section, add the paragraph and the picture
DevRamona/the_Baumesiter pull request #15
Opened 2024-05-29 10:21 UTC by DevRamona

Created the about section containing the paragraph, the yellow image, and made them responsive.

2024-05-29 10:26 UTC, Gasorekibo approved these changes
It looks fine

2024-05-29 10:43 UTC, peninah98 requested changes
Check the feedbacks.

2024-05-29 10:43 UTC, peninah98 commented on src/sections/about.html
> +    <img src="/img/Vector-12.webp">
Can you add the `alt` in case the image is not displayed to show the alt value of the image? 
 `<img src="/img/Vector-12.webp" alt ="image name">`

2024-05-29 10:43 UTC, peninah98 commented on src/sections/about.html
> +  <div class="flex justify-center mt-16 items-center sticky top-0">
This image is too small 
![group 5  reveiws](https://github.com/DevRamona/the_Baumesiter/assets/78850411/51b733a9-7c76-44c5-a37d-7de3ed8ae90e) check the figma and compare to your UI.

2024-05-29 10:57 UTC, peninah98 requested changes
Image is still too  small.

2024-05-29 12:53 UTC, peninah98 requested changes

2024-05-29 12:53 UTC, peninah98 commented on src/sections/about.html
> +    <img  src="/img/Vector-12.webp " alt="yellow-vector">
Can you remove the empty space in the `src` of the image it is still small.

2024-05-29 14:47 UTC, peninah98 requested changes

2024-05-29 14:47 UTC, peninah98 commented on src/sections/about.html
> +  <p class="font-body font-normal pt-36 pb-16 px-10 text-black text-2xl md:pr-8 md:pl-36 md:text-3xl md:px-16 lg:leading-[3.5rem] lg:text-[2.875rem] ">
Why are you using arbitrary values?

2024-05-29 14:47 UTC, peninah98 commented on src/sections/about.html
> +  <p class="font-body font-normal pt-36 pb-16 px-10 text-black text-2xl md:pr-8 md:pl-36 md:text-3xl md:px-16 lg:leading-[3.5rem] lg:text-[2.875rem] ">
Remove the empty spaces after Tailwind CSS classes, it is not a good practice to use arbitrary values

2024-05-29 14:47 UTC, peninah98 commented on src/sections/about.html
> +  <img class="h-24"  src="/img/Vector-12.webp" alt="yellow-vector">
Remove these empty spaces.

2024-05-29 15:25 UTC, Kevin-gram approved these changes
it looks good  on here

2024-05-30 08:33 UTC, peninah98 approved these changes
LGTM

2024-05-30 08:34 UTC, merged