feat:implementing the service section
DevRamona/the_Baumesiter pull request #17
Opened 2024-05-29 15:38 UTC by brendahuwitonze

Here are what this PR does:

2024-05-29 15:47 UTC, DevRamona requested changes
Remove the space here.

2024-05-29 15:47 UTC, Kevin-gram requested changes
check the comments and make some slight changes

2024-05-29 15:47 UTC, Kevin-gram commented on src/output.css
> +<<<<<<< HEAD
you have conflicts here

2024-05-29 15:47 UTC, Kevin-gram commented on src/output.css
>  }
there are conflicts here too

2024-05-29 15:47 UTC, Kevin-gram commented on src/sections/about.html
> +    </div>
Consider removing this here

2024-05-30 13:07 UTC, Gasorekibo requested changes
May  remove those commented codes for good practices?

2024-05-30 13:07 UTC, Gasorekibo commented on ToDo/index.html
> +<p id="targetElement">Original Text</p>  -->
Please consider removing extra comments

2024-05-30 13:11 UTC, Gasorekibo requested changes

2024-05-30 13:11 UTC, Gasorekibo commented on src/sections/service.html
> +        <div class="  md:col-span-1  md:row-span-1 bg-[url('../../img/Vector-5.webp')] md:w-[29.285rem] h-[100%] md:bg-contain bg-contain bg-no-repeat md:mt-0 mt-16 ">
There is an extra white space between classes. May you remove it? Please consider not using arbitrary(%) values as requested in the morning stand-up.

2024-06-05 15:11 UTC, merged