Ft/ft service
DevRamona/the_Baumesiter pull request #24
Opened 2024-06-04 17:32 UTC by Gihozo23

Added service list items
Added the green vector
Added the text and position it on the vector
Made it responsive on three screens ( lg: MacBook Air, md: iPad Pro 11 and sm: iPhone 13 Pro)
<img width="103" alt="sm-og-service" src="https://github.com/DevRamona/the_Baumesiter/assets/109101706/75e2e5e0-76bb-451c-b1a1-0c3040e5d620">

<img width="405" alt="lg-section" src="https://github.com/DevRamona/the_Baumesiter/assets/109101706/83d13305-a714-466e-a423-1f47157961a1">

<img width="224" alt="sm-service" src="https://github.com/DevRamona/the_Baumesiter/assets/109101706/144d9637-1c96-44b2-8306-93e4bf755b5e">

2024-06-04 17:39 UTC, brendahuwitonze reviewed
It's ok with me

2024-06-05 12:07 UTC, kevin-Nk approved these changes
This looks good

2024-06-05 12:46 UTC, AdelineA requested changes
Good job, check the comments below.

2024-06-05 12:46 UTC, AdelineA commented on src/sections/about.html
>    </p>
since you touched this file, you can add the font-style to the paragraph

2024-06-05 12:46 UTC, AdelineA commented on src/sections/service.html
> +    class="w-full space-y-16 font-outfit text-2xl font-medium md:text-4xl lg:col-span-1 lg:row-span-1 lg:text-5xl"
use text-xl for the small screen

2024-06-05 12:46 UTC, AdelineA commented on src/sections/service.html
> +        class="ml-10 w-[17.6rem] pr-10 pt-28 font-outfit text-lg font-light text-primaryColor md:w-[26rem] md:pl-10 md:pr-14 md:pt-40 md:text-xl lg:w-[26rem] lg:pl-10"
use text-xl, and instead of md:w-[26rem] use `w-96`, delete the `lg:w-[26rem] `it's duplicate and delete all duplicate classes

2024-06-05 12:46 UTC, AdelineA commented on tailwind.config.js
> +      },
This is not necessary

2024-06-05 13:34 UTC, Gihozo23 commented on src/sections/about.html
>    </p>
I added the font-outfit on the paragraph

2024-06-05 13:34 UTC, Gihozo23 commented on src/sections/service.html
> +    class="w-full space-y-16 font-outfit text-2xl font-medium md:text-4xl lg:col-span-1 lg:row-span-1 lg:text-5xl"
Thank you, I just used text-xl and it looked too small and I went back on Figma and realized that on the small screen, the text-size is 24px which is equal to 2xl in tailwind. Do I still change to text-xl?
<img width="330" alt="service-Adeline" src="https://github.com/DevRamona/the_Baumesiter/assets/109101706/daecef66-1d7b-4065-880f-7327413d1e2c">

2024-06-05 13:34 UTC, Gihozo23 commented on src/sections/service.html
> +        class="ml-10 w-[17.6rem] pr-10 pt-28 font-outfit text-lg font-light text-primaryColor md:w-[26rem] md:pl-10 md:pr-14 md:pt-40 md:text-xl lg:w-[26rem] lg:pl-10"
Thank you, I just used text-xl and it looked off and I went back on Figma and realized that on the medium screen, the text-size is 18px which is equal to lg in tailwind. Do I still change to text-xl?
<img width="310" alt="service-Adeline2" src="https://github.com/DevRamona/the_Baumesiter/assets/109101706/ff5337a7-b0c3-4943-aa5d-21f10ddd04a4">
I deleted the duplicates, and when I changed the width to 96, the width of the text was reduced considerably and looked horrible, what do I do? 
<img width="215" alt="service-Adeline3" src="https://github.com/DevRamona/the_Baumesiter/assets/109101706/51fa5abb-4bee-4f5b-814b-a3abc01ad87f">

2024-06-05 13:34 UTC, Gihozo23 commented on tailwind.config.js
> +      },
should I delete it? It was for the dev

2024-06-05 13:41 UTC, AdelineA commented on src/sections/service.html
> +    class="w-full space-y-16 font-outfit text-2xl font-medium md:text-4xl lg:col-span-1 lg:row-span-1 lg:text-5xl"
No need, fixed.

2024-06-05 13:46 UTC, AdelineA commented on src/sections/service.html
> +        class="ml-10 w-[17.6rem] pr-10 pt-28 font-outfit text-lg font-light text-primaryColor md:w-[26rem] md:pl-10 md:pr-14 md:pt-40 md:text-xl lg:w-[26rem] lg:pl-10"
width try full and just make sure the text are in the center

2024-06-05 13:49 UTC, AdelineA commented on src/sections/service.html
> +        class="ml-10 w-[17.6rem] pr-10 pt-28 font-outfit text-lg font-light text-primaryColor md:w-[26rem] md:pl-10 md:pr-14 md:pt-40 md:text-xl lg:w-[26rem] lg:pl-10"
for the font-size leave it if you double checked.

2024-06-05 13:50 UTC, AdelineA approved these changes
Check the comment and once everything is okay, merge the PR

2024-06-05 15:11 UTC, merged